In [3]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('leaf.png')

blur = cv2.GaussianBlur(img,(5,5),0)

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(blur),plt.title('Blurred')
plt.xticks([]), plt.yticks([])
plt.show()

In [12]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('leaf.png')
mean = np.mean(img)

blur1 = cv2.GaussianBlur(img,(3,3),0)
blur2 = cv2.GaussianBlur(img,(11,11),0)
blur = (blur1/2)+(blur2/2)

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(blur),plt.title('Blurred')
plt.xticks([]), plt.yticks([])
plt.show()

In [13]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('leaf.png')

blur = cv2.bilateralFilter(img,9,75,75)

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(blur),plt.title('Blurred')
plt.xticks([]), plt.yticks([])
plt.show()

In [120]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('leaf.png',0)

# Output dtype = cv2.CV_8U
sobelx8u = cv2.Sobel(img,cv2.CV_8U,1,0,ksize=5)

# Output dtype = cv2.CV_64F. Then take its absolute and convert to cv2.CV_8U
sobelx64f = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
abs_sobel64f = np.absolute(sobelx64f)
sobel_8u = np.uint8(abs_sobel64f)

plt.subplot(1,3,1),plt.imshow(img,cmap = 'gray')
plt.title('Original'), plt.xticks([]), plt.yticks([])
plt.subplot(1,3,2),plt.imshow(sobelx8u,cmap = 'gray')
plt.title('Sobel CV_8U'), plt.xticks([]), plt.yticks([])
plt.subplot(1,3,3),plt.imshow(sobel_8u,cmap = 'gray')
plt.title('Sobel abs(CV_64F)'), plt.xticks([]), plt.yticks([])

plt.show()

In [35]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

def function():
    
    #print img.shape
    for i in range(0,img.shape[0]):
        for j in range(0,img.shape[1]):
            for k in range(0,img.shape[2]):
                if(gradient_mag[i,j,k] > mean):
                    img[i,j,k]=sharp_dog[i,j,k]
                else:
                    img[i,j,k]=blur_dog[i,j,k]
    #return img
    
def function1():
    for i in range(0,3):
        img[:,:,i] = np.multiply(gamma,img[:,:,i])


original = cv2.imread('leaf.png')
img = original
bilateral = cv2.bilateralFilter(img,9,75,75)
gauss = cv2.GaussianBlur(img,(5,5),0)

sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)
gradient_mag = np.sqrt(np.square(sobelx)+np.square(sobely))
mean = np.mean(gradient_mag)
sharp = cv2.GaussianBlur(img,(3,3),0)
blur = cv2.GaussianBlur(img,(9,9),0)
sharp_dog = sharp - blur

sharp1 = cv2.GaussianBlur(img,(9,9),0)
blur1 = cv2.GaussianBlur(img,(27,27),0)
blur_dog = sharp1 - blur1

a = sharp_dog[:,:,0]+sharp_dog[:,:,1]+sharp_dog[:,:,2]
b = blur_dog[:,:,0]+blur_dog[:,:,1]+blur_dog[:,:,2]
gamma = np.divide(a,b)
         


function()
#function1()

plt.subplot(141),plt.imshow(cv2.imread('leaf.png')),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(142),plt.imshow(img),plt.title('A-DOG')
plt.xticks([]), plt.yticks([])
plt.subplot(243),plt.imshow(bilateral),plt.title('Bilateral')
plt.xticks([]), plt.yticks([])
plt.subplot(244),plt.imshow(gauss),plt.title('Gaussian')
plt.xticks([]), plt.yticks([])
plt.show()



'''cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()'''

C:\Users\Ratul\Anaconda2\envs\dato-env\lib\site-packages\ipykernel\__main__.py:41: RuntimeWarning: divide by zero encountered in divide


"cv2.imshow('image',img)\ncv2.waitKey(0)\ncv2.destroyAllWindows()"

In [34]:
np.divide(np.array([0, 1], dtype=int), np.array([0, 0], dtype=int))


C:\Users\Ratul\Anaconda2\envs\dato-env\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([0, 0])

In [113]:
np.mean(original),mean,np.mean(img),np.mean(sharp),np.mean(blur),original[200,200],img[200,200]

(179.63143888888888,
 755.01311331099953,
 179.63143888888888,
 179.59517222222223,
 179.59634166666666,
 array([ 88, 184, 134], dtype=uint8),
 array([ 88, 184, 134], dtype=uint8))

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

def function():
    

    for i in range(0,img.shape[0]):
        for j in range(0,img.shape[1]):
            for k in range(0,img.shape[2]):
                if(gradient_mag[i,j,k] > mean):
                    img[i,j,k]=sharp_dog[i,j,k]
                else:
                    img[i,j,k]=blur_dog[i,j,k]
                    
def floor():
    
    for i in range(0,img.shape[0]):
        for j in range(0,img.shape[1]):
            for k in range(0,img.shape[2]):
                if(img[i,j,k] > 255):
                    img[i,j,k] = 255
                    


original = cv2.imread('leaf.png')
img = original.astype('uint16')
c1  = cv2.imread('leaf.png')[:,:,0]
c2  = cv2.imread('leaf.png')[:,:,1]
c3  = cv2.imread('leaf.png')[:,:,2]

bilateral = cv2.bilateralFilter(original,13,75,75)
gauss = cv2.GaussianBlur(original,(5,5),0)

sobelx = cv2.Sobel(original,cv2.CV_64F,1,0,ksize=5)
sobely = cv2.Sobel(original,cv2.CV_64F,0,1,ksize=5)
gradient_mag = np.sqrt(np.square(sobelx)+np.square(sobely))
mean = np.mean(gradient_mag)
sharp = cv2.GaussianBlur(original,(3,3),0)
blur = cv2.GaussianBlur(original,(9,9),0)
sharp_dog = (sharp/2) + (blur/2)

sharp1 = cv2.GaussianBlur(original,(9,9),0)
blur1 = cv2.GaussianBlur(original,(27,27),0)
blur_dog = (sharp1/2) + (blur1/2)

a = sharp_dog[:,:,0] + sharp_dog[:,:,1] + sharp_dog[:,:,2]
b = blur_dog[:,:,0] + blur_dog[:,:,1] + blur_dog[:,:,2]
gamma = np.true_divide(a,b)

function()
 

img[:,:,0] = np.multiply(c1,gamma)
img[:,:,1] = np.multiply(c2,gamma)
img[:,:,2] = np.multiply(c3,gamma)


floor()
img = img.astype('uint8')

plt.subplot(141),plt.imshow(cv2.imread('leaf.png')),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(142),plt.imshow(img),plt.title('A-DOG')
plt.xticks([]), plt.yticks([])
plt.subplot(243),plt.imshow(bilateral),plt.title('Bilateral')
plt.xticks([]), plt.yticks([])
plt.subplot(244),plt.imshow(gauss),plt.title('Gaussian')
plt.xticks([]), plt.yticks([])
plt.show()



C:\Users\Ratul\Anaconda2\envs\dato-env\lib\site-packages\ipykernel\__main__.py:49: RuntimeWarning: divide by zero encountered in true_divide
C:\Users\Ratul\Anaconda2\envs\dato-env\lib\site-packages\ipykernel\__main__.py:49: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Ratul\Anaconda2\envs\dato-env\lib\site-packages\ipykernel\__main__.py:54: RuntimeWarning: invalid value encountered in multiply


In [140]:
a[236,499],b[236,499],gamma[236,499],img[236,499],c1[236,499],cv2.imread('leaf.png')[236,499]

(250,
 247,
 1.0121457489878543,
 array([258, 258, 258], dtype=uint16),
 255,
 array([255, 255, 255], dtype=uint8))

In [121]:
np.array(img).shape, img

((240L, 500L, 3L), array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ..., 
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ..., 
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ..., 
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ..., 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ..., 
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ..., 
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ..., 
     